// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: chat.proto

package chatv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerNotice_Type int32

const (
	ServerNotice_TYPE_GENERIC     ServerNotice_Type = 0
	ServerNotice_TYPE_USER_JOINED ServerNotice_Type = 1
	ServerNotice_TYPE_USER_LEFT   ServerNotice_Type = 2
	ServerNotice_TYPE_ERROR       ServerNotice_Type = 3
)

// Enum value maps for ServerNotice_Type.
var (
	ServerNotice_Type_name = map[int32]string{
		0: "TYPE_GENERIC",
		1: "TYPE_USER_JOINED",
		2: "TYPE_USER_LEFT",
		3: "TYPE_ERROR",
	}
	ServerNotice_Type_value = map[string]int32{
		"TYPE_GENERIC":     0,
		"TYPE_USER_JOINED": 1,
		"TYPE_USER_LEFT":   2,
		"TYPE_ERROR":       3,
	}
)

func (x ServerNotice_Type) Enum() *ServerNotice_Type {
	p := new(ServerNotice_Type)
	*p = x
	return p
}

func (x ServerNotice_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerNotice_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[0].Descriptor()
}

func (ServerNotice_Type) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[0]
}

func (x ServerNotice_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerNotice_Type.Descriptor instead.
func (ServerNotice_Type) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{6, 0}
}

// JoinRequest describes the information a client must send to join a room.
type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Room          string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *JoinRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// ChatPayload represents an arbitrary message sent by a client.
type ChatPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Room          string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	TimestampUtc  int64                  `protobuf:"varint,4,opt,name=timestamp_utc,json=timestampUtc,proto3" json:"timestamp_utc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatPayload) Reset() {
	*x = ChatPayload{}
	mi := &file_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatPayload) ProtoMessage() {}

func (x *ChatPayload) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatPayload.ProtoReflect.Descriptor instead.
func (*ChatPayload) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ChatPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatPayload) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *ChatPayload) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatPayload) GetTimestampUtc() int64 {
	if x != nil {
		return x.TimestampUtc
	}
	return 0
}

// LeaveRequest notifies the server that a client wants to disconnect from a room.
type LeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Room          string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	mi := &file_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *LeaveRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LeaveRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

// ClientEnvelope is the input stream wrapper clients use to talk to the server.
type ClientEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ClientEnvelope_Join
	//	*ClientEnvelope_Chat
	//	*ClientEnvelope_Leave
	Message       isClientEnvelope_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEnvelope) Reset() {
	*x = ClientEnvelope{}
	mi := &file_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEnvelope) ProtoMessage() {}

func (x *ClientEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEnvelope.ProtoReflect.Descriptor instead.
func (*ClientEnvelope) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ClientEnvelope) GetMessage() isClientEnvelope_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ClientEnvelope) GetJoin() *JoinRequest {
	if x != nil {
		if x, ok := x.Message.(*ClientEnvelope_Join); ok {
			return x.Join
		}
	}
	return nil
}

func (x *ClientEnvelope) GetChat() *ChatPayload {
	if x != nil {
		if x, ok := x.Message.(*ClientEnvelope_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *ClientEnvelope) GetLeave() *LeaveRequest {
	if x != nil {
		if x, ok := x.Message.(*ClientEnvelope_Leave); ok {
			return x.Leave
		}
	}
	return nil
}

type isClientEnvelope_Message interface {
	isClientEnvelope_Message()
}

type ClientEnvelope_Join struct {
	Join *JoinRequest `protobuf:"bytes,1,opt,name=join,proto3,oneof"`
}

type ClientEnvelope_Chat struct {
	Chat *ChatPayload `protobuf:"bytes,2,opt,name=chat,proto3,oneof"`
}

type ClientEnvelope_Leave struct {
	Leave *LeaveRequest `protobuf:"bytes,3,opt,name=leave,proto3,oneof"`
}

func (*ClientEnvelope_Join) isClientEnvelope_Message() {}

func (*ClientEnvelope_Chat) isClientEnvelope_Message() {}

func (*ClientEnvelope_Leave) isClientEnvelope_Message() {}

// JoinAck confirms that the user joined the requested room.
type JoinAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Room           string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	WelcomeMessage string                 `protobuf:"bytes,3,opt,name=welcome_message,json=welcomeMessage,proto3" json:"welcome_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JoinAck) Reset() {
	*x = JoinAck{}
	mi := &file_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinAck) ProtoMessage() {}

func (x *JoinAck) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinAck.ProtoReflect.Descriptor instead.
func (*JoinAck) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

func (x *JoinAck) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinAck) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *JoinAck) GetWelcomeMessage() string {
	if x != nil {
		return x.WelcomeMessage
	}
	return ""
}

// Broadcast envelope for server -> client communication.
type ServerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ServerEvent_Joined
	//	*ServerEvent_Broadcast
	//	*ServerEvent_Notice
	Event         isServerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{5}
}

func (x *ServerEvent) GetEvent() isServerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ServerEvent) GetJoined() *JoinAck {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Joined); ok {
			return x.Joined
		}
	}
	return nil
}

func (x *ServerEvent) GetBroadcast() *ChatPayload {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Broadcast); ok {
			return x.Broadcast
		}
	}
	return nil
}

func (x *ServerEvent) GetNotice() *ServerNotice {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Notice); ok {
			return x.Notice
		}
	}
	return nil
}

type isServerEvent_Event interface {
	isServerEvent_Event()
}

type ServerEvent_Joined struct {
	Joined *JoinAck `protobuf:"bytes,1,opt,name=joined,proto3,oneof"`
}

type ServerEvent_Broadcast struct {
	Broadcast *ChatPayload `protobuf:"bytes,2,opt,name=broadcast,proto3,oneof"`
}

type ServerEvent_Notice struct {
	Notice *ServerNotice `protobuf:"bytes,3,opt,name=notice,proto3,oneof"`
}

func (*ServerEvent_Joined) isServerEvent_Event() {}

func (*ServerEvent_Broadcast) isServerEvent_Event() {}

func (*ServerEvent_Notice) isServerEvent_Event() {}

// ServerNotice conveys system-level announcements (errors, user events).
type ServerNotice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ServerNotice_Type      `protobuf:"varint,1,opt,name=type,proto3,enum=chat.v1.ServerNotice_Type" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Room          string                 `protobuf:"bytes,4,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerNotice) Reset() {
	*x = ServerNotice{}
	mi := &file_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerNotice) ProtoMessage() {}

func (x *ServerNotice) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerNotice.ProtoReflect.Descriptor instead.
func (*ServerNotice) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{6}
}

func (x *ServerNotice) GetType() ServerNotice_Type {
	if x != nil {
		return x.Type
	}
	return ServerNotice_TYPE_GENERIC
}

func (x *ServerNotice) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServerNotice) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ServerNotice) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

var File_chat_proto protoreflect.FileDescriptor

const file_chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"chat.proto\x12\achat.v1\"]\n" +
	"\vJoinRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\"y\n" +
	"\vChatPayload\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12#\n" +
	"\rtimestamp_utc\x18\x04 \x01(\x03R\ftimestampUtc\";\n" +
	"\fLeaveRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\"\xa2\x01\n" +
	"\x0eClientEnvelope\x12*\n" +
	"\x04join\x18\x01 \x01(\v2\x14.chat.v1.JoinRequestH\x00R\x04join\x12*\n" +
	"\x04chat\x18\x02 \x01(\v2\x14.chat.v1.ChatPayloadH\x00R\x04chat\x12-\n" +
	"\x05leave\x18\x03 \x01(\v2\x15.chat.v1.LeaveRequestH\x00R\x05leaveB\t\n" +
	"\amessage\"_\n" +
	"\aJoinAck\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\x12'\n" +
	"\x0fwelcome_message\x18\x03 \x01(\tR\x0ewelcomeMessage\"\xa9\x01\n" +
	"\vServerEvent\x12*\n" +
	"\x06joined\x18\x01 \x01(\v2\x10.chat.v1.JoinAckH\x00R\x06joined\x124\n" +
	"\tbroadcast\x18\x02 \x01(\v2\x14.chat.v1.ChatPayloadH\x00R\tbroadcast\x12/\n" +
	"\x06notice\x18\x03 \x01(\v2\x15.chat.v1.ServerNoticeH\x00R\x06noticeB\a\n" +
	"\x05event\"\xd9\x01\n" +
	"\fServerNotice\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.chat.v1.ServerNotice.TypeR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04room\x18\x04 \x01(\tR\x04room\"R\n" +
	"\x04Type\x12\x10\n" +
	"\fTYPE_GENERIC\x10\x00\x12\x14\n" +
	"\x10TYPE_USER_JOINED\x10\x01\x12\x12\n" +
	"\x0eTYPE_USER_LEFT\x10\x02\x12\x0e\n" +
	"\n" +
	"TYPE_ERROR\x10\x032K\n" +
	"\vChatService\x12<\n" +
	"\aChannel\x12\x17.chat.v1.ClientEnvelope\x1a\x14.chat.v1.ServerEvent(\x010\x01B6Z4github.com/lechitz/chat-grpc/api/proto/chatv1;chatv1b\x06proto3"

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData []byte
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)))
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_chat_proto_goTypes = []any{
	(ServerNotice_Type)(0), // 0: chat.v1.ServerNotice.Type
	(*JoinRequest)(nil),    // 1: chat.v1.JoinRequest
	(*ChatPayload)(nil),    // 2: chat.v1.ChatPayload
	(*LeaveRequest)(nil),   // 3: chat.v1.LeaveRequest
	(*ClientEnvelope)(nil), // 4: chat.v1.ClientEnvelope
	(*JoinAck)(nil),        // 5: chat.v1.JoinAck
	(*ServerEvent)(nil),    // 6: chat.v1.ServerEvent
	(*ServerNotice)(nil),   // 7: chat.v1.ServerNotice
}
var file_chat_proto_depIdxs = []int32{
	1, // 0: chat.v1.ClientEnvelope.join:type_name -> chat.v1.JoinRequest
	2, // 1: chat.v1.ClientEnvelope.chat:type_name -> chat.v1.ChatPayload
	3, // 2: chat.v1.ClientEnvelope.leave:type_name -> chat.v1.LeaveRequest
	5, // 3: chat.v1.ServerEvent.joined:type_name -> chat.v1.JoinAck
	2, // 4: chat.v1.ServerEvent.broadcast:type_name -> chat.v1.ChatPayload
	7, // 5: chat.v1.ServerEvent.notice:type_name -> chat.v1.ServerNotice
	0, // 6: chat.v1.ServerNotice.type:type_name -> chat.v1.ServerNotice.Type
	4, // 7: chat.v1.ChatService.Channel:input_type -> chat.v1.ClientEnvelope
	6, // 8: chat.v1.ChatService.Channel:output_type -> chat.v1.ServerEvent
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	file_chat_proto_msgTypes[3].OneofWrappers = []any{
		(*ClientEnvelope_Join)(nil),
		(*ClientEnvelope_Chat)(nil),
		(*ClientEnvelope_Leave)(nil),
	}
	file_chat_proto_msgTypes[5].OneofWrappers = []any{
		(*ServerEvent_Joined)(nil),
		(*ServerEvent_Broadcast)(nil),
		(*ServerEvent_Notice)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		EnumInfos:         file_chat_proto_enumTypes,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
